def main():
    print("Hello, World 2!")
    print("Hello, World 3!")
    print("Hello, World 4!")
    print("Hello, World 5!")
    print("Hello, World 6!")
    print("Hello, World 7!")
    print("Hello, World 8!")
    print("Hello, World 9!")
    print("Hello, World 10!")
    print("Hello, World 11!")
    print("Hello, World 12!")
    print("Hello, World 13!")
    print("Hello, World 14!")
    print("Hello, World 15!")
    print("Hello, World 16!")
    print("Hello, World 17!")
    print("Hello, World 18!")
    print("Hello, World 19!")
    print("Hello, World 20!")
    print("Hello, World 21!")
    print("Hello, World 22!")
    print("Hello, World 23!")
    print("Hello, World 24!")
    print("Hello, World 25!")
    print("Hello, World 26!")
    print("Hello, World 27!")
    print("Hello, World 28!")
    print("Hello, World 29!")
    print("Hello, World 30!")
    print("Hello, World 31!")
    print("Hello, World 32!")
    print("Hello, World 33!")
    print("Hello, World 34!")
    print("Hello, World 35!")
    print("Hello, World 36!")
    print("Hello, World 37!")


if __name__ == "__main__":
    main()
